build:
	cat codemirror.js codemirror-hb.js hbio/hbio.js hbio/bin.js hbio/utf8.js playground.js playground-embed.js | uglifyjs > playground-full.js && \
	cat style.css runner.css codemirror.css codemirror-*.css > playground-full.css
